Section "Monitor"
    Identifier "Monitor-HDMI-1"
    Option "IgnoreEDID" "true"
    Option "NoDDC" "true"
    Option "Enable" "true"
    Modeline "640x480_60" 25.20 640 656 752 800 480 490 492 525 -hsync -vsync
    Option "PreferredMode" "640x480_60"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "modesetting"
    Option "Monitor-HDMI-1" "Monitor-HDMI-1"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card0"
    Monitor "Monitor-HDMI-1"
    DefaultDepth 24
    SubSection "Display"
        Modes "640x480_60"
    EndSubSection
EndSection
