Section "Monitor"
    Identifier "Monitor-Composite-1"
    Option "IgnoreEDID" "true"
    Option "NoDDC" "true"
    Option "Enable" "true"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "modesetting"
    Option "Monitor-Composite-1" "Monitor-Composite-1"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card0"
    Monitor "Monitor-Composite-1"
    DefaultDepth 24
EndSection
